--Creación tabla CANTÓN y secuencia

CREATE TABLE TB_CANTON (
    ID_CANTON          NUMBER       PRIMARY KEY,
    NOMBRE             VARCHAR2(20) NOT NULL,
    ID_PROVINCIA       NUMBER       REFERENCES TB_PROVINCIA(ID_PROVINCIA),
    FECHA_MODIFICACION DATE,
    MODIFICADO_POR     VARCHAR2(20),
    FECHA_CREACION     DATE,
    CREADO_POR         VARCHAR2(20),
    ID_ESTADO          NUMBER       REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE SEQUENCE SEQ_TB_CANTON START WITH 1 INCREMENT BY 1;

--Creación de CRUD

--Insert
CREATE OR REPLACE PROCEDURE SP_TB_CANTON_INSERT(
    p_nombre IN TB_CANTON.NOMBRE%TYPE,
    p_id_provincia IN TB_CANTON.ID_PROVINCIA%TYPE,
    p_id_estado IN TB_CANTON.ID_ESTADO%TYPE,
    p_creado_por IN TB_CANTON.CREADO_POR%TYPE
)
AS
BEGIN
    INSERT INTO TB_CANTON(
        ID_CANTON, NOMBRE, ID_PROVINCIA, ID_ESTADO, CREADO_POR, FECHA_CREACION
    ) VALUES (
        SEQ_TB_CANTON.NEXTVAL, p_nombre, p_id_provincia, p_id_estado, p_creado_por, SYSDATE
    );
END;
/

--Update
CREATE OR REPLACE PROCEDURE SP_TB_CANTON_UPDATE(
    p_id_canton IN TB_CANTON.ID_CANTON%TYPE,
    p_nombre IN TB_CANTON.NOMBRE%TYPE,
    p_id_provincia IN TB_CANTON.ID_PROVINCIA%TYPE,
    p_id_estado IN TB_CANTON.ID_ESTADO%TYPE,
    p_modificado_por IN TB_CANTON.MODIFICADO_POR%TYPE
)
AS
BEGIN
    UPDATE TB_CANTON
    SET NOMBRE = p_nombre,
        ID_PROVINCIA = p_id_provincia,
        ID_ESTADO = p_id_estado,
        MODIFICADO_POR = p_modificado_por,
        FECHA_MODIFICACION = SYSDATE
    WHERE ID_CANTON = p_id_canton;
END;
/

--Delete
CREATE OR REPLACE PROCEDURE SP_TB_CANTON_DELETE(
    p_id_canton IN TB_CANTON.ID_CANTON%TYPE
)
AS
BEGIN
    DELETE FROM TB_CANTON WHERE ID_CANTON = p_id_canton;
END;
/

--Select
CREATE OR REPLACE PROCEDURE SP_TB_CANTON_SELECT(
    p_result OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_CANTON;
END;
/

--Creación de Vista

CREATE OR REPLACE VIEW VW_TB_CANTON AS
SELECT 
    C.ID_CANTON,
    C.NOMBRE AS NOMBRE_CANTON,
    P.NOMBRE AS NOMBRE_PROVINCIA,
    E.NOMBRE AS ESTADO,
    C.CREADO_POR,
    C.FECHA_CREACION,
    C.MODIFICADO_POR,
    C.FECHA_MODIFICACION
FROM TB_CANTON C
LEFT JOIN TB_PROVINCIA P ON C.ID_PROVINCIA = P.ID_PROVINCIA
LEFT JOIN TB_ESTADO E ON C.ID_ESTADO = E.ID_ESTADO;
/

--Creación de Función

CREATE OR REPLACE FUNCTION FN_TB_CANTON_GET_NOMBRE(
    p_id_canton IN TB_CANTON.ID_CANTON%TYPE
)
RETURN VARCHAR2
AS
    v_nombre TB_CANTON.NOMBRE%TYPE;
BEGIN
    SELECT NOMBRE INTO v_nombre
    FROM TB_CANTON
    WHERE ID_CANTON = p_id_canton;

    RETURN v_nombre;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

--Creación de Procedimiento y Cursor

CREATE OR REPLACE PROCEDURE SP_TB_CANTON_CURSOR(
    p_result OUT SYS_REFCURSOR
)
AS
    CURSOR C_CANTON IS
        SELECT ID_CANTON, NOMBRE, ID_PROVINCIA, ID_ESTADO,
               CREADO_POR, FECHA_CREACION,
               MODIFICADO_POR, FECHA_MODIFICACION
        FROM TB_CANTON;
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_CANTON;
END;
/