--Creación tabla DISTRITO y secuencia

CREATE TABLE TB_DISTRITO (
    ID_DISTRITO        NUMBER       PRIMARY KEY,
    NOMBRE             VARCHAR2(20) NOT NULL,
    ID_CANTON          NUMBER       REFERENCES TB_CANTON(ID_CANTON),
    CREADO_POR         VARCHAR2(20),
    FECHA_MODIFICACION DATE,
    MODIFICADO_POR     VARCHAR2(20),
    FECHA_CREACION     DATE,
    ID_ESTADO          NUMBER       REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE SEQUENCE SEQ_TB_DISTRITO START WITH 1 INCREMENT BY 1;

--Creación de CRUD

--Insert
CREATE OR REPLACE PROCEDURE SP_TB_DISTRITO_INSERT(
    p_nombre IN TB_DISTRITO.NOMBRE%TYPE,
    p_id_canton IN TB_DISTRITO.ID_CANTON%TYPE,
    p_id_estado IN TB_DISTRITO.ID_ESTADO%TYPE,
    p_creado_por IN TB_DISTRITO.CREADO_POR%TYPE
)
AS
BEGIN
    INSERT INTO TB_DISTRITO(
        ID_DISTRITO, NOMBRE, ID_CANTON, ID_ESTADO, CREADO_POR, FECHA_CREACION
    ) VALUES (
        SEQ_TB_DISTRITO.NEXTVAL, p_nombre, p_id_canton, p_id_estado, p_creado_por, SYSDATE
    );
END;
/

--Update
CREATE OR REPLACE PROCEDURE SP_TB_DISTRITO_UPDATE(
    p_id_distrito IN TB_DISTRITO.ID_DISTRITO%TYPE,
    p_nombre IN TB_DISTRITO.NOMBRE%TYPE,
    p_id_canton IN TB_DISTRITO.ID_CANTON%TYPE,
    p_id_estado IN TB_DISTRITO.ID_ESTADO%TYPE,
    p_modificado_por IN TB_DISTRITO.MODIFICADO_POR%TYPE
)
AS
BEGIN
    UPDATE TB_DISTRITO
    SET NOMBRE = p_nombre,
        ID_CANTON = p_id_canton,
        ID_ESTADO = p_id_estado,
        MODIFICADO_POR = p_modificado_por,
        FECHA_MODIFICACION = SYSDATE
    WHERE ID_DISTRITO = p_id_distrito;
END;
/

--Delete
CREATE OR REPLACE PROCEDURE SP_TB_DISTRITO_DELETE(
    p_id_distrito IN TB_DISTRITO.ID_DISTRITO%TYPE
)
AS
BEGIN
    DELETE FROM TB_DISTRITO WHERE ID_DISTRITO = p_id_distrito;
END;
/

--Select
CREATE OR REPLACE PROCEDURE SP_TB_DISTRITO_SELECT(
    p_result OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_DISTRITO;
END;
/

--Creación de Vista

CREATE OR REPLACE VIEW VW_TB_DISTRITO AS
SELECT 
    D.ID_DISTRITO,
    D.NOMBRE AS NOMBRE_DISTRITO,
    C.NOMBRE AS NOMBRE_CANTON,
    E.NOMBRE AS ESTADO,
    D.CREADO_POR,
    D.FECHA_CREACION,
    D.MODIFICADO_POR,
    D.FECHA_MODIFICACION
FROM TB_DISTRITO D
LEFT JOIN TB_CANTON C ON D.ID_CANTON = C.ID_CANTON
LEFT JOIN TB_ESTADO E ON D.ID_ESTADO = E.ID_ESTADO;
/

--Creación de Función

CREATE OR REPLACE FUNCTION FN_TB_DISTRITO_GET_NOMBRE(
    p_id_distrito IN TB_DISTRITO.ID_DISTRITO%TYPE
)
RETURN VARCHAR2
AS
    v_nombre TB_DISTRITO.NOMBRE%TYPE;
BEGIN
    SELECT NOMBRE INTO v_nombre
    FROM TB_DISTRITO
    WHERE ID_DISTRITO = p_id_distrito;

    RETURN v_nombre;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

--Creación de Procedimiento y Cursor

CREATE OR REPLACE PROCEDURE SP_TB_DISTRITO_CURSOR(
    p_result OUT SYS_REFCURSOR
)
AS
    CURSOR C_DISTRITO IS
        SELECT ID_DISTRITO, NOMBRE, ID_CANTON, ID_ESTADO,
               CREADO_POR, FECHA_CREACION,
               MODIFICADO_POR, FECHA_MODIFICACION
        FROM TB_DISTRITO;
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_DISTRITO;
END;
/