--Creación tabla ESTADO y secuencia

CREATE TABLE TB_ESTADO (
    ID_ESTADO          NUMBER       PRIMARY KEY,
    NOMBRE             VARCHAR2(20) NOT NULL,
    DESCRIPCION        VARCHAR2(250),
    CREADO_POR         VARCHAR2(20),
    FECHA_MODIFICACION DATE,
    MODIFICADO_POR     VARCHAR2(20),
    FECHA_CREACION     DATE
);

CREATE SEQUENCE SEQ_TB_ESTADO START WITH 1 INCREMENT BY 1;

--Creación de CRUD

--Insert
CREATE OR REPLACE PROCEDURE SP_TB_ESTADO_INSERT(
    p_nombre IN TB_ESTADO.NOMBRE%TYPE,
    p_creado_por IN TB_ESTADO.CREADO_POR%TYPE
)
AS
BEGIN
    INSERT INTO TB_ESTADO(
        ID_ESTADO, NOMBRE, DESCRIPCION, CREADO_POR, FECHA_CREACION
    ) VALUES (
        SEQ_TB_ESTADO.NEXTVAL, p_nombre, p_descripcion, p_creado_por, SYSDATE
    );
END;
/

--Update
CREATE OR REPLACE PROCEDURE SP_TB_ESTADO_UPDATE(
    p_id_estado IN TB_ESTADO.ID_ESTADO%TYPE,
    p_nombre IN TB_ESTADO.NOMBRE%TYPE,
    p_descripcion IN TB_ESTADO.DESCRIPCION%TYPE,
    p_modificado_por IN TB_ESTADO.MODIFICADO_POR%TYPE
)
AS
BEGIN
    UPDATE TB_ESTADO
    SET NOMBRE = p_nombre,
        DESCRIPCION = p_descripcion,
        MODIFICADO_POR = p_modificado_por,
        FECHA_MODIFICACION = SYSDATE
    WHERE ID_ESTADO = p_id_estado;
END;
/

--Delete
CREATE OR REPLACE PROCEDURE SP_TB_ESTADO_DELETE(
    p_id_estado IN TB_ESTADO.ID_ESTADO%TYPE
)
AS
BEGIN
    DELETE FROM TB_ESTADO WHERE ID_ESTADO = p_id_estado;
END;
/

--Select
CREATE OR REPLACE PROCEDURE SP_TB_ESTADO_SELECT(
    p_result OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_ESTADO;
END;
/

--Creación de Vista

CREATE OR REPLACE VIEW VW_TB_ESTADO AS
SELECT 
    ID_ESTADO,
    NOMBRE,
    DESCRIPCION,
    CREADO_POR,
    FECHA_CREACION,
    MODIFICADO_POR,
    FECHA_MODIFICACION
FROM TB_ESTADO;
/

--Creación de Función

CREATE OR REPLACE FUNCTION FN_TB_ESTADO_GET_NOMBRE(
    p_id_estado IN TB_ESTADO.ID_ESTADO%TYPE
)
RETURN VARCHAR2
AS
    v_nombre TB_ESTADO.NOMBRE%TYPE;
BEGIN
    SELECT NOMBRE INTO v_nombre
    FROM TB_ESTADO
    WHERE ID_ESTADO = p_id_estado;

    RETURN v_nombre;
EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        RETURN NULL;
END;
/

--Creación de Procedimiento y Cursor

CREATE OR REPLACE PROCEDURE SP_TB_ESTADO_CURSOR(
    p_result OUT SYS_REFCURSOR
)
AS
    CURSOR C_ESTADO IS
        SELECT ID_ESTADO, NOMBRE, CREADO_POR, FECHA_CREACION,
               MODIFICADO_POR, FECHA_MODIFICACION
        FROM TB_ESTADO;
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_ESTADO;
END;
/