--Creación tabla PROVEEDOR y secuencia

CREATE TABLE TB_PROVEEDOR (
    ID_PROVEEDOR       NUMBER       PRIMARY KEY,
    NOMBRE             VARCHAR2(20) NOT NULL,
    CORREO_ELECTRONICO VARCHAR2(250),
    NUM_TELEFONO       VARCHAR2(15),
    ID_DISTRITO          NUMBER       REFERENCES TB_DISTRITO(ID_DISTRITO),
    DETALLE_DIRECCION  VARCHAR2(250),
    CREADO_POR         VARCHAR2(20),
    FECHA_MODIFICACION DATE,
    MODIFICADO_POR     VARCHAR2(20),
    FECHA_CREACION     DATE,
    ID_ESTADO          NUMBER       REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE SEQUENCE SEQ_TB_PROVEEDOR START WITH 1 INCREMENT BY 1;

--Creación de CRUD

--Insert
CREATE OR REPLACE PROCEDURE SP_TB_PROVEEDOR_INSERT(
    p_nombre IN TB_PROVEEDOR.NOMBRE%TYPE,
    p_correo IN TB_PROVEEDOR.CORREO_ELECTRONICO%TYPE,
    p_telefono IN TB_PROVEEDOR.NUM_TELEFONO%TYPE,
    p_id_distrito IN TB_PROVEEDOR.ID_DISTRITO%TYPE,
    p_direccion IN TB_PROVEEDOR.DETALLE_DIRECCION%TYPE,
    p_id_estado IN TB_PROVEEDOR.ID_ESTADO%TYPE,
    p_creado_por IN TB_PROVEEDOR.CREADO_POR%TYPE
)
AS
BEGIN
    INSERT INTO TB_PROVEEDOR(
        ID_PROVEEDOR, NOMBRE, CORREO_ELECTRONICO, NUM_TELEFONO, ID_DISTRITO, DETALLE_DIRECCION, 
        ID_ESTADO, CREADO_POR, FECHA_CREACION
    ) VALUES (
        SEQ_TB_PROVEEDOR.NEXTVAL, p_nombre, p_correo, p_telefono, p_id_distrito, p_direccion,
        p_id_estado, p_creado_por, SYSDATE
    );
END;
/

--Update
CREATE OR REPLACE PROCEDURE SP_TB_PROVEEDOR_UPDATE(
    p_id_proveedor IN TB_PROVEEDOR.ID_PROVEEDOR%TYPE,
    p_nombre IN TB_PROVEEDOR.NOMBRE%TYPE,
    p_correo IN TB_PROVEEDOR.CORREO_ELECTRONICO%TYPE,
    p_telefono IN TB_PROVEEDOR.NUM_TELEFONO%TYPE,
    p_id_distrito IN TB_PROVEEDOR.ID_DISTRITO%TYPE,
    p_direccion IN TB_PROVEEDOR.DETALLE_DIRECCION%TYPE,
    p_id_estado IN TB_PROVEEDOR.ID_ESTADO%TYPE,
    p_modificado_por IN TB_PROVEEDOR.MODIFICADO_POR%TYPE
)
AS
BEGIN
    UPDATE TB_PROVEEDOR
    SET NOMBRE = p_nombre,
        CORREO_ELECTRONICO = p_correo,
        NUM_TELEFONO = p_telefono,
        ID_DISTRITO = p_id_distrito,
        DETALLE_DIRECCION = p_direccion,
        ID_ESTADO = p_id_estado,
        MODIFICADO_POR = p_modificado_por,
        FECHA_MODIFICACION = SYSDATE
    WHERE ID_PROVEEDOR = p_id_proveedor;
END;
/

--Delete
CREATE OR REPLACE PROCEDURE SP_TB_PROVEEDOR_DELETE(
    p_id_proveedor IN TB_PROVEEDOR.ID_PROVEEDOR%TYPE
)
AS
BEGIN
    DELETE FROM TB_PROVEEDOR WHERE ID_PROVEEDOR = p_id_proveedor;
END;
/

--Select
CREATE OR REPLACE PROCEDURE SP_TB_PROVEEDOR_SELECT(
    p_result OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_PROVEEDOR;
END;
/

--Creación de Vista

CREATE OR REPLACE VIEW VW_TB_PROVEEDOR AS
SELECT 
    PR.ID_PROVEEDOR,
    PR.NOMBRE,
    PR.CORREO_ELECTRONICO,
    PR.NUM_TELEFONO,
    PR.DETALLE_DIRECCION,
    E.NOMBRE AS ESTADO,
    PR.CREADO_POR,
    PR.FECHA_CREACION,
    PR.MODIFICADO_POR,
    PR.FECHA_MODIFICACION
FROM TB_PROVEEDOR PR
LEFT JOIN TB_ESTADO E ON PR.ID_ESTADO = E.ID_ESTADO
LEFT JOIN TB_DISTRITO D ON PR.ID_DISTRITO = D.ID_DISTRITO;
/

--Creación de Función

CREATE OR REPLACE FUNCTION FN_TB_PROVEEDOR_GET_NOMBRE(
    p_id_proveedor IN TB_PROVEEDOR.ID_PROVEEDOR%TYPE
)
RETURN VARCHAR2
AS
    v_nombre TB_PROVEEDOR.NOMBRE%TYPE;
BEGIN
    SELECT NOMBRE INTO v_nombre
    FROM TB_PROVEEDOR
    WHERE ID_PROVEEDOR = p_id_proveedor;

    RETURN v_nombre;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

--Creación de Procedimiento y Cursor

CREATE OR REPLACE PROCEDURE SP_TB_PROVEEDOR_CURSOR(
    p_result OUT SYS_REFCURSOR
)
AS
    CURSOR C_PROVEEDOR IS
        SELECT ID_PROVEEDOR, NOMBRE, CORREO_ELECTRONICO,
               NUM_TELEFONO, DETALLE_DIRECCION, ID_ESTADO,
               CREADO_POR, FECHA_CREACION,
               MODIFICADO_POR, FECHA_MODIFICACION
        FROM TB_PROVEEDOR;
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_PROVEEDOR;
END;
/