--Creación tabla PROVINCIA y secuencia

CREATE TABLE TB_PROVINCIA (
    ID_PROVINCIA       NUMBER       PRIMARY KEY,
    NOMBRE             VARCHAR2(20) NOT NULL,
    CREADO_POR         VARCHAR2(20),
    FECHA_MODIFICACION DATE,
    MODIFICADO_POR     VARCHAR2(20),
    FECHA_CREACION     DATE,
    ID_ESTADO          NUMBER       REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE SEQUENCE SEQ_TB_PROVINCIA START WITH 1 INCREMENT BY 1;

--Creación de CRUD

--Insert
CREATE OR REPLACE PROCEDURE SP_TB_PROVINCIA_INSERT(
    p_nombre IN TB_PROVINCIA.NOMBRE%TYPE,
    p_id_estado IN TB_PROVINCIA.ID_ESTADO%TYPE,
    p_creado_por IN TB_PROVINCIA.CREADO_POR%TYPE
)
AS
BEGIN
    INSERT INTO TB_PROVINCIA(
        ID_PROVINCIA, NOMBRE, ID_ESTADO, CREADO_POR, FECHA_CREACION
    ) VALUES (
        SEQ_TB_PROVINCIA.NEXTVAL, p_nombre, p_id_estado, p_creado_por, SYSDATE
    );
END;
/

--Update
CREATE OR REPLACE PROCEDURE SP_TB_PROVINCIA_UPDATE(
    p_id_provincia IN TB_PROVINCIA.ID_PROVINCIA%TYPE,
    p_nombre IN TB_PROVINCIA.NOMBRE%TYPE,
    p_id_estado IN TB_PROVINCIA.ID_ESTADO%TYPE,
    p_modificado_por IN TB_PROVINCIA.MODIFICADO_POR%TYPE
)
AS
BEGIN
    UPDATE TB_PROVINCIA
    SET NOMBRE = p_nombre,
        ID_ESTADO = p_id_estado,
        MODIFICADO_POR = p_modificado_por,
        FECHA_MODIFICACION = SYSDATE
    WHERE ID_PROVINCIA = p_id_provincia;
END;
/

--Delete
CREATE OR REPLACE PROCEDURE SP_TB_PROVINCIA_DELETE(
    p_id_provincia IN TB_PROVINCIA.ID_PROVINCIA%TYPE
)
AS
BEGIN
    DELETE FROM TB_PROVINCIA WHERE ID_PROVINCIA = p_id_provincia;
END;
/

--Select
CREATE OR REPLACE PROCEDURE SP_TB_PROVINCIA_SELECT(
    p_result OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_PROVINCIA;
END;
/

--Creación de Vista

CREATE OR REPLACE VIEW VW_TB_PROVINCIA AS
SELECT 
    P.ID_PROVINCIA,
    P.NOMBRE AS NOMBRE_PROVINCIA,
    E.NOMBRE AS ESTADO,
    P.CREADO_POR,
    P.FECHA_CREACION,
    P.MODIFICADO_POR,
    P.FECHA_MODIFICACION
FROM TB_PROVINCIA P
LEFT JOIN TB_ESTADO E ON P.ID_ESTADO = E.ID_ESTADO;
/

--Creación de Función

CREATE OR REPLACE FUNCTION FN_TB_PROVINCIA_GET_NOMBRE(
    p_id_provincia IN TB_PROVINCIA.ID_PROVINCIA%TYPE
)
RETURN VARCHAR2
AS
    v_nombre TB_PROVINCIA.NOMBRE%TYPE;
BEGIN
    SELECT NOMBRE INTO v_nombre
    FROM TB_PROVINCIA
    WHERE ID_PROVINCIA = p_id_provincia;

    RETURN v_nombre;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

--Creación de Procedimiento y Cursor

CREATE OR REPLACE PROCEDURE SP_TB_PROVINCIA_CURSOR(
    p_result OUT SYS_REFCURSOR
)
AS
    CURSOR C_PROVINCIA IS
        SELECT ID_PROVINCIA, NOMBRE, ID_ESTADO,
               CREADO_POR, FECHA_CREACION,
               MODIFICADO_POR, FECHA_MODIFICACION
        FROM TB_PROVINCIA;
BEGIN
    OPEN p_result FOR
        SELECT * FROM TB_PROVINCIA;
END;
/